// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xymiyjelfsokodcfltvp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh5bWl5amVsZnNva29kY2ZsdHZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NTkxMjksImV4cCI6MjA3MDMzNTEyOX0.MGcpjbjHnWOUaN03xqO1M10z67gVnJge87Sr6TwJ8Dc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});